language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

cache: pip

install:
  - "pip install . pytest pytest-cov flake8"

before_script:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"

script:
  - "flake8 --ignore=F401 tests ppping"
  - "py.test --cov ppping tests/"

after_script:
  - "./cc-test-reporter after-build"