sudo: true

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

addons:
  apt:
    packages:
      - iputils-ping
      - net-tools

install:
  - "pip install pipenv"
  - "pipenv install --dev

before_script:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"

script:
  - "pipenv run flake8 tests ppping"
  - "pipenv run pytest --cov ppping tests/"

after_script:
  - "coverage xml"
  - "./cc-test-reporter after-build"
