__title__ = 'ppping'
__description__ = 'ping monitoring tool written in Python'
__url__ = 'http://github.com/johejo/ppping'
__version__ = '0.1.9'
__author__ = 'Mitsuo Heijo'
__author_email__ = 'mitsuo_h@outlook.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Mitsuo Heijo'
